name: whackavirus
description: Whack A Virus

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  condition: ^0.0.8
  rflutter_alert: ^2.0.2
  auto_size_text: ^2.1.0
  url_launcher: ^5.4.5
  package_info: ^2.0.0
  share: ^2.0.1
  page_transition: ^1.1.7+6
  intl: ^0.17.0
  flutter_linkify: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "ic_launcher"
  ios: false
  image_path: "images/virus.png"

flutter_native_splash:
  image: "images/virus.png"
  color: "FFFFFF"
  fill: true

flutter:
  uses-material-design: true
  assets:
    - images/
    - sounds/