name: whackavirus
description: Whack A Virus

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  condition: ^0.0.7
  rflutter_alert: ^1.0.3
  auto_size_text: ^2.1.0
  url_launcher: ^5.4.5
  package_info: ^0.4.0+17
  share: ^0.6.4
  page_transition: ^1.1.5
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  path_provider: ^1.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.7.0+2
  build_runner: ^1.9.0


flutter:
  uses-material-design: true

  assets:
    - images/

