name: whackadorbesh
description: Whack A Dorbesh

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  conditioned: ^0.1.0-dev.1
  rflutter_alert: ^2.0.7
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/